### ISSUE TITLE
It's not changing automatically the theme

### ISSUE THREAD

**Issue by matutin0** [skhzhang/time-based-themes#10]
Hi Simon!
When I found your extension really loved it, it's just what I was looking for. But for some reason it's not working anymore. I've been some time now switching it off and on in order to make it change to the proper theme. I've try both options, de auto and the manual, but any of them seem to work...

It would be great if you can take a look to find out why might this be happening. I use Mac, Firefox 74.0 (even though it already happened before updating to this version).

Thanks a lot for your time and work, Simon! Hope you can solve this.
Greetings from the Canary Islands, Spain!

**Comment by matutin0** [comment]
Oh wait!!!
I missed the option "Check only on start-up and setup"! Now understood that it means that the theme will change only depending on the time you start-up the browser! So I guess if unchecked it should change automatically 😅

Will see if tomorrow it works properly and if so will let you know!

**Comment by skhzhang** [comment]
Thanks for the update and letting me know! I'll make a change to make it more clear.

Hope you are enjoying the extension!

**Comment by skhzhang** [comment]
Made setting more clear with fd31bef
