### ISSUE TITLE
"Change theme based on system theme" does not take effect until FF restart

### ISSUE THREAD

**Issue by haselwarter** [skhzhang/time-based-themes#15]
On Linux, changing the Gtk3 theme does not lead to a change in appearance until Firefox is closed and restarted.

**Comment by kajeli** [comment]
Working perfectly for me !

I'm running Firefox 83.0 and using Xfce4's settings daemon and tools to change my GTK theme.
I used to have a similar problem when I was running an older version of Firefox and when I wasn't running an xsettings daemon.

![time-based-themes](https://user-images.githubusercontent.com/72570482/102373282-522ec680-3fc0-11eb-9dc2-d421adadf1ac.gif)

**Comment by skhzhang** [comment]
Thank you @kajeli ! @haselwarter , please let us know if you're running Firefox 83.0 or later and still seeing the same problem.

**Comment by icidasset** [comment]
I had the same problem on Mac OS with Firefox v84.0.2, had to restart as well.

**Comment by xplosionmind** [comment]
> I had the same problem on Mac OS with Firefox v84.0.2, had to restart as well.

I am having this problem in Firefox 86 on MacOS 11. The theme change goes crazy!

**Comment by Alex0007** [comment]
I'm having this problem on Firefox 90, MacOS 11

I guess it's related to this [one](https://github.com/skhzhang/time-based-themes/blob/master/js/common.js#L73). Window focus event doesn't work for theme changed in background. It should be additionally checked by interval

**Comment by graphit0** [comment]
I experience the same issue in this environment:

OS: Kubuntu 21.04 x86_64
DE: Plasma 5.22.5 
WM: KWin
FF: 94.0 64-bit (non snap package)

**Comment by skhzhang** [comment]
If anyone is running Firefox 95 (or higher), please try out 1.4.0 and let me know if that fixes any issues you have with the "Change theme based on system theme" option.

Thanks!

**Comment by graphit0** [comment]
![image](https://user-images.githubusercontent.com/44114323/145556164-25cf3d4a-e47a-4d2e-a673-c831ce5d5735.png)

https://user-images.githubusercontent.com/44114323/145557615-9d1a89ea-7b4a-4146-835e-732d4d3002e2.mp4

Changing the system theme still doesn't work but extension is functional: it does change FF theme to dark if I change daytime theme to dark regardless of the system theme.

The new permissions have been accepted on first prompt.

extension: 1.4.0 but for some reason it still states on settings page that it is 1.3.0
OS: Kubuntu 21.04 x86_64
DE: Plasma 5.22.5
WM: KWin
FF: 95.0 64-bit (non snap package)

**Comment by haselwarter** [comment]
For the record, running an xsettings daemon as @kajeli mentioned does indeed solve the issue for me. I'm using sway and gsd-xsettings provided by gnome-setting-daemon.

**Comment by skhzhang** [comment]
Fixed with version 1.4.1 (https://github.com/skhzhang/time-based-themes/commit/95361c8e635b45b2f49fc661893cc74399f10970, https://github.com/skhzhang/time-based-themes/commit/c350c46ae3b56fc19b153319ada787e84d736281, https://github.com/skhzhang/time-based-themes/commit/c22df5863233328e846e21a1c2387474f181e7d7, https://github.com/skhzhang/time-based-themes/commit/97bd8d749befe24c230411baadab7b32d17bb8aa). Please open a new issue and reference this one if there are any issues. Thanks!
