### ISSUE TITLE
Make time checking more automatic

### ISSUE THREAD

**Issue by tlannaax** [skhzhang/time-based-themes#3]
Is it necessary to check time every fixed time interval? This seems so hacking and unnatural. It should be enough to set a timer event based on sunrise/sunset times.
Moreover, it would be nice if the extension could get sunrise/sunset times from web services based on location, like what windows 10's night light schedule does.

**Comment by skhzhang** [comment]
Good point! Setting a timer makes sense and would definitely be an upgrade to what it does right now. I'll look into it.

As for getting sunrise/sunset times based on location, that may require getting Location permissions from the user--and that's something to consider. But it would make using the addon a lot simpler. I'll also look into this as well and see if it's possible.

Thanks for the feedback!

**Comment by skhzhang** [comment]
This should be fixed with version 1.0.6 which is pending approval right. The change was made in 836a656393fcc04331ebd21e7b28025fad301b06

As for the feedback about getting sunrise/sunset times from web services, I split that to a new issue #4 and I'm going to close this one.

Thanks!
Simon
