### ISSUE TITLE
Change themes based on system theme.

### ISSUE THREAD

**Issue by chrisgross** [skhzhang/time-based-themes#8]
So I know you recently added a feature to automatically switch themes based on geolocation, but an even better feature Dark Reader just added to their extension is to change themes dynamically based on the current system theme. I'm not sure how much work it is, but this would be the last bit needed to make these two extensions work perfectly and seamlessly with MacOS's dark theme.

Honestly, if Firefox would just make the horrible light version (where everything is light but the tab bar) of their default dynamic theme the same as their light theme, none of this would really be necessary for me, but I imagine others would like to use different themes.

**Comment by paulvt** [comment]
I was just about to add an issue requesting the ability to have an offset with respect to the sunrise/sunset time as the OS/system theme itself already switches some time before sunset and after sunrise. I guess if it would just follow the system theme then that is even better!
Currently I sometimes end up with a dark system theme but still very white pages 🙂.

**Comment by derekschinke** [comment]
Just wanted to bump this. This is exactly what I want, because this extension doesn't change at the exact same time as the rest of my computer.

**Comment by skhzhang** [comment]
This is added in 5bd7f05 and released with 1.2.0, which I just uploaded to addons.mozilla.org.

Please let me know any feedback you have for this. It's not working as well as I'd like on my Windows 10 machine. It's something I want to look into more in the future. Let me know how it works for you!

**Comment by derekschinke** [comment]
Didn't work for me on macOS unfortunately, the system changed from light to dark automatically and automaticDark didn't pick up on it and stayed light. This is with the "Change themes based on the system theme" setting enabled

**Comment by paulvt** [comment]
Unfortunately, also not in Debian. Using addon version 1.2.1 on Firefox 76.0.
